### ISSUE TITLE
Add a Screenshot

### ISSUE THREAD

**Issue by zicklag** [Naxela/PPM#2]
This is really, cool! I've seen this repo before, but I didn't understand exactly what it did from the description. Your screenshot that you posted on the forums would be perfect, can you add it to the README?

![naxela-armory-plugin](https://user-images.githubusercontent.com/25393315/49552086-a6721c80-f8b7-11e8-84f6-0f2053a53a92.gif)

**Comment by Naxela** [comment]
Added the screenshot. Updated the readme - Will add more screenshots and a proper description once Armory v0.6 arrives :)
